services:
  doc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: privacy-genie-doc
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      HF_HOME: /models/huggingface
    volumes:
      - .:/app
      - embedding-models:/models
    networks:
      - privacy-genie-network

volumes:
  embedding-models:

networks:
  privacy-genie-network:
    external: true
