"""프로젝트 루트를 기준으로 한 기본 입력·출력 경로."""
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DOCUMENTS_DIR = PROJECT_ROOT / "documents"
SOURCE_DIR = DOCUMENTS_DIR / "source"
PROCESSED_DIR = DOCUMENTS_DIR / "processed"
EXTRACTED_DIR = PROCESSED_DIR
LAW_DIR = SOURCE_DIR / "laws"
ACT_SOURCE_PATH = LAW_DIR / "privacy.hwpx"
DECREE_SOURCE_PATH = LAW_DIR / "privacy_decree.hwpx"
DEFAULT_SOURCE_PATH = ACT_SOURCE_PATH
STRUCTURE_FILENAME = "law_structure.json"
CHUNKS_FILENAME = "chunks.json"
CLASSIFICATION_FILENAME = "classified_paragraphs.txt"
PREVIEW_FILENAME = "embedding_preview.txt"
STRUCTURE_PATH = EXTRACTED_DIR / STRUCTURE_FILENAME
CHUNKS_PATH = EXTRACTED_DIR / CHUNKS_FILENAME
CLASSIFICATION_PATH = EXTRACTED_DIR / CLASSIFICATION_FILENAME
PREVIEW_PATH = EXTRACTED_DIR / PREVIEW_FILENAME
TEXT_ENCODING = "utf-8"
PREVIEW_SEPARATOR = "=" * 60
PREVIEW_DIVIDER = "-" * 60
